baseurl = "https://crsmithdev.com/"
languageCode = "en-us"
title = "Chris Smith"
theme = "crsmithdev"
preserveTaxonomyNames = true
paginate = 3
googleAnalytics = "UA-40826256-2"

[blackfriday]
hrefTargetBlank = true

[[params.social]]
url = "https://github.com/crsmithdev"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/crsmithdev"
fa_icon = "fa-twitter"

[[params.social]]
url = "https://linkedin.com/in/crsmithdev"
fa_icon = "fa-linkedin"

[[params.social]]
url = "https://keybase.io/crsmithdev"
fa_icon = "fa-key"

[[params.social]]
url = "mailto:crsmithdev@gmail.com"
fa_icon = "fa-envelope"

[params.highlight]
style = "atom-one-light"
languages = ["python"]
